### ISSUE TITLE
DeviceID

### ISSUE THREAD

**Issue by vladtsit** [spongioblast/node-red-contrib-local-mihome#2]
Hi, I have zhimi.humidifier.ca4 device. How to get it Device ID?

**Comment by Shaquu** [comment]
@vladtsit 
https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

**Comment by spongioblast** [comment]
The cloud toke extractor didn't always seem to give me the correct toke for local operations. I used the android app that stored the token on the phone, this seems to work more consistently. Check out this guide:
https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md
